# Generated by Django 4.2 on 2023-09-28 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortener.service


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shorturl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500, verbose_name="URL")),
                (
                    "identifier",
                    models.CharField(
                        default=shortener.service.shortcode,
                        editable=False,
                        max_length=8,
                        unique=True,
                        verbose_name="Short URL",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "shorturl",
                "verbose_name_plural": "shorturls",
            },
        ),
    ]
